### ISSUE TITLE
Transaction scope can work with nest-cls

### ISSUE THREAD

**Issue by atmeshwar-classic** [zhuravlevma/unit-of-work-ddd#1]
Hi @zhuravlevma , Thank you for sharing this amazing piece of work with us. You have helped me crack unit of work with Prisma.

I opened this issue to let you know that your first approach with cls-hooked also works with a few modifications. You would need to add [nestjs-cls](https://papooch.github.io/nestjs-cls/) and enable it globally and we can easily share the prisma transaction object without the need to pass it as an arg into each repository.

I'm sharing some of the code here for your reference.

`export abstract class UnitOfWork {
  abstract runInTransaction<R>(fn: () => Promise<R>): Promise<R>;
}
`

`import { ClsService, Terminal } from "nestjs-cls";

@Injectable({ scope: Scope.REQUEST })
export class PrismaTransactionScope implements UnitOfWork {
  constructor(
    private readonly prisma: PrismaService,
    private readonly cls: ClsService<{
      prisma: Terminal<Prisma.TransactionClient>;
    }>,
  ) {}

  get manager() {
    return this.cls.get("prisma");
  }

  async runInTransaction<T>(fn: () => Promise<T>): Promise<T> {
    return await this.prisma.$transaction(async (manager) => {
      this.cls.set("prisma", manager);
      return await fn();
    });
  }
}`

`import { ClsModule } from "nestjs-cls";

@Module({
  imports: [
    ClsModule.forRoot({ global: true, middleware: { mount: true } }),
  ],
  controllers: [AppController],
})
export class AppModule {}`

Kindly let me know if it works for you.

Regards,
Atmeshwar

**Comment by zhuravlevma** [comment]
Hi @atmeshwar-classic, there is a drawback with cls-hooked that can occasionally occur, and it may be challenging to catch the bug.

If there are multiple parallel transactions within a single request, for example, using Promise.all, the behavior will be undefined! For example:

The request arrives.
The first transaction within Promise.all begins execution. The second one starts too.
The first one finishes quite quickly (there were few database queries), while the second one is still running.
Here lies the problem! Both transactions will be looking at the same transaction instance!
Of course, this example may be a bit contrived, and you may not encounter it, but it's something to keep in mind. That's why I decided to avoid using magic. I personally tested everything initially with cls-hooked.|

Regards,
Maksim))
